"""
train_naive_bayes.py
Numeral 3.2 - Naive Bayes model for Sentinel-2 land-cover classification.

Input:
    training_dataset.tsv generated by dataset.py

Outputs:
    results/nb_confusion_matrix.csv
    results/nb_confusion_matrix.png
    results/nb_classification_report.csv
    results/nb_summary_metrics.csv
    results/nb_model.joblib

Run:
    python train_naive_bayes.py
"""

from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    cohen_kappa_score,
    confusion_matrix,
    f1_score,
)
from sklearn.model_selection import GridSearchCV, StratifiedKFold, train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder, StandardScaler


RANDOM_STATE = 42
INPUT_TSV = Path("training_dataset.tsv")
OUTPUT_DIR = Path("results")

BAND_COLUMNS = [
    "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B8A", "B11", "B12"
]
LABEL_COLUMN = "label"


def load_training_data(tsv_path: Path) -> tuple[pd.DataFrame, pd.Series]:
    """Loads the TSV dataset and returns spectral features X and labels y."""
    if not tsv_path.exists():
        raise FileNotFoundError(
            f"Could not find {tsv_path}. Run `python dataset.py` first."
        )

    df = pd.read_csv(tsv_path, sep="\t")

    missing = [c for c in BAND_COLUMNS + [LABEL_COLUMN] if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in {tsv_path}: {missing}")

    df = df[BAND_COLUMNS + [LABEL_COLUMN]].copy()
    df[BAND_COLUMNS] = df[BAND_COLUMNS].apply(pd.to_numeric, errors="coerce")
    df = df.dropna(subset=BAND_COLUMNS + [LABEL_COLUMN])

    X = df[BAND_COLUMNS]
    y = df[LABEL_COLUMN].astype(str)
    return X, y


def save_confusion_matrix_png(cm: np.ndarray, labels: np.ndarray, output_path: Path) -> None:
    """Saves a readable confusion matrix figure using matplotlib."""
    fig, ax = plt.subplots(figsize=(8, 6))
    image = ax.imshow(cm)
    fig.colorbar(image, ax=ax)

    ax.set_title("Naive Bayes - Confusion Matrix")
    ax.set_xlabel("Predicted class")
    ax.set_ylabel("True class")
    ax.set_xticks(np.arange(len(labels)))
    ax.set_yticks(np.arange(len(labels)))
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.set_yticklabels(labels)

    threshold = cm.max() / 2 if cm.size and cm.max() > 0 else 0
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(
                j,
                i,
                str(cm[i, j]),
                ha="center",
                va="center",
                color="white" if cm[i, j] > threshold else "black",
            )

    fig.tight_layout()
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)


def train_and_evaluate_naive_bayes() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    X, y_text = load_training_data(INPUT_TSV)

    encoder = LabelEncoder()
    y = encoder.fit_transform(y_text)
    class_names = encoder.classes_

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.30,
        random_state=RANDOM_STATE,
        stratify=y,
    )

    pipeline = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            ("model", GaussianNB()),
        ]
    )

    param_grid = {
        "model__var_smoothing": np.logspace(-12, -6, 13)
    }

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

    search = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        scoring="f1_macro",
        cv=cv,
        n_jobs=-1,
        refit=True,
        return_train_score=True,
    )
    search.fit(X_train, y_train)

    best_model = search.best_estimator_
    y_pred = best_model.predict(X_test)

    cm = confusion_matrix(y_test, y_pred, labels=np.arange(len(class_names)))
    accuracy = accuracy_score(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    f1_macro = f1_score(y_test, y_pred, average="macro")
    f1_weighted = f1_score(y_test, y_pred, average="weighted")

    cm_df = pd.DataFrame(
        cm,
        index=[f"true_{name}" for name in class_names],
        columns=[f"pred_{name}" for name in class_names],
    )
    cm_df.to_csv(OUTPUT_DIR / "nb_confusion_matrix.csv")
    save_confusion_matrix_png(cm, class_names, OUTPUT_DIR / "nb_confusion_matrix.png")

    report = classification_report(
        y_test,
        y_pred,
        target_names=class_names,
        output_dict=True,
        zero_division=0,
    )
    pd.DataFrame(report).transpose().to_csv(OUTPUT_DIR / "nb_classification_report.csv")

    summary = pd.DataFrame(
        [
            {
                "model": "Naive Bayes (GaussianNB)",
                "best_var_smoothing": search.best_params_["model__var_smoothing"],
                "cv_best_f1_macro": search.best_score_,
                "test_overall_accuracy": accuracy,
                "test_kappa": kappa,
                "test_f1_macro": f1_macro,
                "test_f1_weighted": f1_weighted,
                "train_samples": len(X_train),
                "test_samples": len(X_test),
                "features": ", ".join(BAND_COLUMNS),
            }
        ]
    )
    summary.to_csv(OUTPUT_DIR / "nb_summary_metrics.csv", index=False)

    joblib.dump(
        {
            "model": best_model,
            "label_encoder": encoder,
            "band_columns": BAND_COLUMNS,
            "class_names": class_names.tolist(),
        },
        OUTPUT_DIR / "nb_model.joblib",
    )

    print("Naive Bayes training finished.")
    print(f"Best parameters: {search.best_params_}")
    print(f"Overall Accuracy: {accuracy:.4f}")
    print(f"Kappa Coefficient: {kappa:.4f}")
    print(f"F1 Macro: {f1_macro:.4f}")
    print(f"F1 Weighted: {f1_weighted:.4f}")
    print(f"Outputs saved in: {OUTPUT_DIR.resolve()}")


if __name__ == "__main__":
    train_and_evaluate_naive_bayes()
